services:
  postgres:
    image: postgres:16-alpine
    container_name: accounting-db
    environment:
      POSTGRES_DB: accounting_saas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: accounting-mq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    container_name: accounting-cache
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    container_name: accounting-storage
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  postgres_data: